### PR TITLE
cocopods 1.0.0 

### PR DESCRIPTION
**Pull request by welkiner**
i diff cocoapods between 0.39.0 and 1.0.0 ,and try to fix it。it works~！(⊙o⊙)…

### CODE REVIEW

**Comment by amorde** [comment]
Hey @dustywusty any thoughts on this?

Looks good, one things that concerns me though is that it breaks compatibility and therefore forces a dependency on CocoaPods `1.0.0`

**Comment by dustywusty** [comment]
Hey guys, super super sorry for being so delayed in looking at this PR. 😞 

Give me a day or so to catch up, check this out, and I'll have some more comments this weekend. 🍰

**Comment by amorde** [comment]
@dustywusty Sorry to bother again but was wondering if you have any updates on this. It would be great to support 1.0 as CocoaPods is moving pretty fast these days

**Comment by dustywusty** [comment]
Hey @amorde, I'm super sorry for the lack of activity, it seems like every time I sit down to look at this something catches on fire. 🔥 🔥 🔥 

As it stands, I'm guessing this just breaks pre 1.0 support for cocoapods, but everything seems to be gravy in cocoapods latest?

If that's the case I'll merge, release, and push right now.

**Comment by amorde** [comment]
@dustywusty No problem! I feel you haha

I believe that's the case, but to be honest I don't have an easy way to test it on my own right now

**Pull request merged**
